# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: docker.adeo.no:5000/fo/frontendlogger
replicas:
  min: 2
  max: 4
  cpuThresholdPercentage: 50
port: 8080
resources:
  limits:
    cpu: 3
healthcheck:
  liveness:
    path: frontendlogger/internal/isAlive
    initialDelay: 60
  readiness:
    path: frontendlogger/internal/selftest
    initialDelay: 60
prometheus:
  enabled: true
  path: frontendlogger/internal/metrics
fasitResources:
  exposed:
  - alias: frontendloggerSbsApi
    resourceType: restservice
    path: /frontendlogger/api
team: oppfolging
