# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: docker.adeo.no:5000/fo/frontendlogger
team: pus
replicas:
  min: 2
  max: 4
  cpuThresholdPercentage: 50
port: 8080
resources:
  limits:
    cpu: 3
    memory: 768Mi
  requests:
    cpu: 200m
    memory: 512Mi
healthcheck:
  liveness:
    path: frontendlogger/internal/isAlive
    initialDelay: 20
  readiness:
    path: frontendlogger/internal/isReady
    initialDelay: 20
prometheus:
  enabled: true
  path: frontendlogger/internal/metrics
fasitResources:
  used:
  - alias: appdynamics
    resourceType: applicationproperties
  - alias: loadbalancer:arbeidsplassen-frontendlogger
    resourceType: loadbalancerconfig
  - alias: loadbalancer:person-frontendlogger
    resourceType: loadbalancerconfig
  - alias: loadbalancer:arbeidsplassen-frontendlogger
    resourceType: loadbalancerconfig
  exposed:
  - alias: frontendloggerSbsApi
    resourceType: restservice
    path: /frontendlogger/api
alertProfiles:
 - common-java-modules

