kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: frontendlogger
  namespace: default
  labels:
    team: pto
  cluster: prod-sbs
spec:
  image: docker.pkg.github.com/navikt/frontendlogger/frontendlogger:{{version}}
  ingresses:
    - https://www.nav.no/frontendlogger
    - https://frontendlogger.nais.oera-q.local
  port: 8080
  liveness:
    path: frontendlogger/internal/isAlive
    initialDelay: 60
  readiness:
    path: frontendlogger/internal/isReady
    initialDelay: 60
  prometheus:
    enabled: true
    path: frontendlogger/internal/metrics
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: 200m
      memory: 512Mi