kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: frontendlogger
  namespace: default
  labels:
    team: pto
  cluster: prod-sbs
spec:
  image: docker.pkg.github.com/navikt/frontendlogger/frontendlogger:{{version}}
  ingresses:
    - https://www.nav.no/frontendlogger
    - https://frontendlogger.nais.oera.no
    - https://tjenester.nav.no/frontendlogger
  port: 8080
  liveness:
    path: frontendlogger/internal/isAlive
    initialDelay: 120
  readiness:
    path: frontendlogger/internal/isReady
    initialDelay: 120
  prometheus:
    enabled: true
    path: frontendlogger/internal/metrics
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: 200m
      memory: 512Mi
  env:
    - name: APP_ENVIRONMENT_NAME
      value: p
    - name: "cors.allowed.origins"
      value: ".nav.no"
